main: com.carlgo11.banhammer.BanHammer
name: ${project.name}
version: ${project.version}
author: Carlgo11
description: ${project.description}
website: ${project.url}
api-version: "1.15"

permissions:
  banhammer.ban:
    default: op
    description: Permission to use the banhammer.
  banhammer.kill:
    default: op
    description: Permission to use the killhammer.
  banhammer.kick:
    default: op
    description: Permission to use the kickhammer.
  banhammer.*:
    default: op
    description: Permission to use all the hammers.
    children:
      banhammer.ban: true
      banhammer.ebola: true
      banhammer.kick: true
